# src/ingest/build_index.py
"""Indexing pipeline for PubMed abstracts.

This script reads the JSONL file generated by ``fetch_pubmed.py``, converts each
record into a :class:`langchain.schema.Document`, splits long abstracts into
manageable chunks, embeds the chunks with OpenAI's ``text-embedding-3-small``
model, and stores them in a persistent ChromaDB collection.

Requirements
------------
- ``python-dotenv`` – loads the OpenAI API key from a ``.env`` file.
- ``langchain`` / ``langchain‑community`` – Document, TextSplitter, embeddings.
- ``chromadb`` – persistent vector store.

Run with::
    poetry run python src/ingest/build_index.py
"""

import json
import os
from pathlib import Path
from typing import List

from dotenv import load_dotenv
try:
    from langchain_core.documents import Document
except ImportError:
    try:
        from langchain.schema import Document
    except ImportError:
        from langchain.docstore.document import Document
try:
    from langchain_text_splitters import RecursiveCharacterTextSplitter
except ImportError:
    from langchain.text_splitter import RecursiveCharacterTextSplitter
try:
    from langchain_openai import OpenAIEmbeddings
except ImportError:
    try:
        from langchain.embeddings.openai import OpenAIEmbeddings
    except ImportError:
        from langchain.embeddings import OpenAIEmbeddings
try:
    from langchain_chroma import Chroma
except ImportError:
    try:
        from langchain_community.vectorstores import Chroma
    except ImportError:
        from langchain.vectorstores import Chroma

# ---------------------------------------------------------------------------
# Configuration (editable)
# ---------------------------------------------------------------------------
DATA_PATH = Path(__file__).parents[2] / "data" / "corpus" / "pubmed_abstracts.jsonl"
CHROMA_DIR = Path(__file__).parents[2] / "chroma_db"
CHROMA_COLLECTION_NAME = "pubmed"
CHUNK_SIZE = 800
CHUNK_OVERLAP = 100
# ---------------------------------------------------------------------------

def load_abstracts(jsonl_path: Path) -> List[Document]:
    """Load PubMed abstracts from a JSON‑Lines file.

    Each line is a JSON object with the keys ``pmid``, ``title``, ``authors``,
    ``journal``, ``year`` and ``abstract``.  The ``abstract`` field becomes the
    document ``page_content`` while the remaining fields are stored in the
    ``metadata`` dict.
    """
    documents: List[Document] = []
    with jsonl_path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            record = json.loads(line)
            metadata = {
                "pmid": record.get("pmid"),
                "title": record.get("title"),
                "journal": record.get("journal"),
                "year": record.get("year"),
                "authors": record.get("authors"),
            }
            doc = Document(page_content=record.get("abstract", ""), metadata=metadata)
            documents.append(doc)
    return documents


def split_documents(docs: List[Document]) -> List[Document]:
    """Split each document into smaller chunks.

    A ``RecursiveCharacterTextSplitter`` is used with the configured chunk size
    and overlap.  The original metadata is propagated to every chunk.
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", " ", ""]
    )
    chunked_docs: List[Document] = []
    for doc in docs:
        chunks = splitter.split_documents([doc])
        chunked_docs.extend(chunks)
    return chunked_docs


def embed_and_store(docs: List[Document]):
    """Create embeddings and persist them to a Chroma collection.

    The function loads the OpenAI API key from ``.env`` (or the environment) and
    uses the ``text-embedding-3-small`` model.  If the collection already exists,
    it is overwritten with the new data.
    """
    # Load .env – the file should contain ``OPENAI_API_KEY=...``
    load_dotenv()

    embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

    # Ensure the persistence directory exists
    CHROMA_DIR.mkdir(parents=True, exist_ok=True)

    # Initialise or replace the collection
    vectordb = Chroma(
        embedding_function=embeddings,
        persist_directory=str(CHROMA_DIR),
        collection_name=CHROMA_COLLECTION_NAME,
    )
    # If the collection already has data we delete it to avoid duplicates
    if vectordb._collection.count() > 0:
        print(f"Existing collection found ({vectordb._collection.count()} vectors). Deleting…")
        vectordb.delete_collection()
        vectordb = Chroma(
            embedding_function=embeddings,
            persist_directory=str(CHROMA_DIR),
            collection_name=CHROMA_COLLECTION_NAME,
        )

    # Add documents in batches for a smoother progress display
    batch_size = 100
    total = len(docs)
    for i in range(0, total, batch_size):
        batch = docs[i : i + batch_size]
        vectordb.add_documents(batch)
        print(f"Added {i + len(batch)} / {total} chunks")

    # Persist to disk
    vectordb.persist()
    print("Indexing complete. Vectors persisted to", CHROMA_DIR)


def main():
    print("Loading abstracts from", DATA_PATH)
    raw_docs = load_abstracts(DATA_PATH)
    print(f"Loaded {len(raw_docs)} abstracts.")

    print("Splitting abstracts into chunks...")
    chunked_docs = split_documents(raw_docs)
    print(f"Created {len(chunked_docs)} chunks (size~{CHUNK_SIZE} chars).")

    print("Embedding chunks and storing in ChromaDB...")
    embed_and_store(chunked_docs)

    print("Finished. Total chunks stored:", len(chunked_docs))


if __name__ == "__main__":
    main()
